kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: greeting-console
spec:
  nodeSelector: {}
  strategy:
    type: Docker
  source:
    type: Git
    git:
      uri: 'https://github.com/mhca3465/do400-greeting-console'
      ref: main
  output:
    to:
      kind: DockerImage
      name: quay.io/makoto_hayase_ca/greeting-console
    pushSecret:
      name: bWFrb3RvX2hheWFzZV9jYTphYlg5VFk1bFI4RnkwcUw5MFRINUxMYk1Ea0RzOExrb2VRazRKT1prTUJkeWRBL1ZmU2s2TEJmTU5adW5ZUmlJ
